### ISSUE TITLE
non-existent parameter "media_url_prefix"

### ISSUE THREAD

**Issue by AykutCevik** [ClickAndMortar/AdvancedCsvConnectorBundle#13]
Hello,

First thank you for sharing your extension. I wanted to give it a try and ran it but got a server error:

> The service "candm_advanced_csv_connector.processor.normalization.advanced_product" has a dependency on a non-existent parameter "media_url_prefix"

Did I miss something to install or configure? I went through your description so far.

**Comment by simoncarre** [comment]
Hello,

Thank you for your feedback! I just added some details in the README for this parameter.

This parameter must be added to your project to generate clean visual URL's during export (you can just add an empty parameter if you are not using it)

**Comment by AykutCevik** [comment]
Hello @simoncarre,
I've added it but also had to add `data_in_directory`. What is this exactly for?
Also I've tried to create a profile but got the following JS error when opening the edit page for that certain profile:
```
pim/job/common/edit/field/textarea is missing from the registry - include it in your requirejs.yml and clear the app cache

Uncaught Error: 
The module "pim/job/common/edit/field/textarea" is undefined.
Most of the time it's because it's not well registered in your requirejs.yml file.
Here is the documentation to fix this problem
```
Already cleared the cache and run the generations. Ideas?

**Comment by simoncarre** [comment]
Hello @AykutCevik 

I have removed usage of `data_in_directory` parameter in last release.
This parameter was used for storage directory during CSV split operation (to prevent Akeneo from processing large files). The directory is now dynamically.

For textarea error, I have updated README file (you need to add `new ClickAndMortar\AdvancedEnrichBundle\ClickAndMortarAdvancedEnrichBundle(),` in your `AppKernel.php` file)

**Comment by haxcop** [comment]
@simoncarre HI - I'm Facing this exact issue but as I'm a newbie , could you please explain me in detail how can I solve the error on on akeneo v2.3 ?
