### ISSUE TITLE
update to 3.1 or 3.0

### ISSUE THREAD

**Issue by Philippe-M** [ClickAndMortar/AdvancedCsvConnectorBundle#14]
Hello, is there an update of the connector to make it compatible with Akeneo 3.1 or 3.0?

**Comment by simoncarre** [comment]
Hello @Philippe-M,

Our bundle is now avaible for Akeneo 3.* ;)

**Comment by Philippe-M** [comment]
Thank you, but not for an installable version on the branch 3.0? It seems to me that versions 3.1 and 3.2 are not with TLS support while the 3.0 branch is TLS?

**Comment by simoncarre** [comment]
Hello @Philippe-M 
The bundle has not been tested on version 3.0 but it must work without too much issues (for version 1.5 or 1.6)

Akeneo 3.2 is now a LTS version: https://www.akeneo.com/fr/blog/akeneo-introduces-a-simpler-product-release-cycle/

**Comment by Philippe-M** [comment]
Oops I had read wrong for 3.2.

Thank you.
