### ISSUE TITLE
Installation description issue

### ISSUE THREAD

**Issue by RiderTwix** [ClickAndMortar/AdvancedCsvConnectorBundle#17]
Hi,
first of all I wanna thank you for your efforts and sharing your work. 
The installation instructions seem not to be fully correct. Is it really a "," at the end of the line? The specific lines need to be terminated by a ";", right? Please see below.

new Pim\Bundle\CustomEntityBundle\PimCustomEntityBundle(),
new ClickAndMortar\AdvancedCsvConnectorBundle\ClickAndMortarAdvancedCsvConnectorBundle(),

However, even with a ";" I get an error when updating the database. 

PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "PimCustomEntityBundle" from namespace "Pim\Bundle\CustomEntityBundle".
Did you forget a "use" statement for another namespace? in /home/sven/akeneo/pim-community-standard/app/AppKernel.php:40

The functions inside the AppKernel.php looks with the two added lines like this:

    public function registerBundles()
    {
        $bundles = $this->registerProjectBundles();

        if (in_array($this->getEnvironment(), array('dev', 'test', 'behat'))) {
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Symfony\Bundle\WebServerBundle\WebServerBundle();
            $bundles[] = new Pim\Bundle\CustomEntityBundle\PimCustomEntityBundle();
            $bundles[] = new ClickAndMortar\AdvancedCsvConnectorBundle\ClickAndMortarAdvancedCsvConnectorBundle();
        }
            
        $bundles = array_merge(
            $this->getSymfonyBundles(),
            $this->getOroDependencies(),
            $this->getOroBundles(),
            $this->getPimDependenciesBundles(),
            $this->getPimBundles(),
            $bundles
        );

        return $bundles;
    }

**Comment by aloupfor** [comment]
Hi,

> The installation instructions seem not to be fully correct. Is it really a "," at the end of the line? The specific lines need to be terminated by a ";", right? Please see below.

The README describe how to enable a bundle on a Symfony project.
It should describe how to enable a bundle on an Akeneo project (`AppKernel.php` is different).
Thank for pointing this out.

From https://github.com/akeneo-labs/CustomEntityBundle#installation, the best way to enable the bundles should be in AppKernel.php:
```
    protected function registerProjectBundles()
    {
        return [
            // your app bundles should be registered here
            new \Pim\Bundle\CustomEntityBundle\PimCustomEntityBundle(),
            new ClickAndMortar\AdvancedCsvConnectorBundle\ClickAndMortarAdvancedCsvConnectorBundle(),
        ];
    }
```



Regarding the error:
> PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "PimCustomEntityBundle" from namespace "Pim\Bundle\CustomEntityBundle".
Did you forget a "use" statement for another namespace? in /home/sven/akeneo/pim-community-standard/app/AppKernel.php:40

Did you install the bundle using :
> $ composer require clickandmortar/advanced-csv-connector-bundle

?

**Comment by RiderTwix** [comment]
Hi,
I checked and the bundle is currently installed. If I move your lines for the AppKernel.php to this position: 
`
protected function registerProjectBundles()
    {
        return [
            // your app bundles should be registered here
            new \Pim\Bundle\CustomEntityBundle\PimCustomEntityBundle(),
            new ClickAndMortar\AdvancedCsvConnectorBundle\ClickAndMortarAdvancedCsvConnectorBundle(),
        ];
    }
`

I get the following errors in the /var/log/akeneo_daemon.err.log

  GNU nano 2.9.3                                                                                          akeneo_daemon.err.log                                                                                                      

`PHP Fatal error:  Uncaught Error: Class 'Pim\Bundle\CustomEntityBundle\PimCustomEntityBundle' not found in /home/sven/akeneo/pim-community-standard/app/AppKernel.php:24
Stack trace:

#0 /home/sven/akeneo/pim-community-standard/app/AppKernel.php(34): AppKernel->registerProjectBundles()
#1 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(488): AppKernel->registerBundles()
#2 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#3 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
#4 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), $
PHP Fatal error:  Uncaught Error: Class 'Pim\Bundle\CustomEntityBundle\PimCustomEntityBundle' not found in /home/sven/akeneo/pim-community-standard/app/AppKernel.php:24
Stack trace:

#0 /home/sven/akeneo/pim-community-standard/app/AppKernel.php(34): AppKernel->registerProjectBundles()
#1 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(488): AppKernel->registerBundles()
#2 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#3 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
#4 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), $
PHP Fatal error:  Uncaught Error: Class 'Pim\Bundle\CustomEntityBundle\PimCustomEntityBundle' not found in /home/sven/akeneo/pim-community-standard/app/AppKernel.php:24
Stack trace:

#0 /home/sven/akeneo/pim-community-standard/app/AppKernel.php(34): AppKernel->registerProjectBundles()
#1 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(488): AppKernel->registerBundles()
#2 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#3 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
#4 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), $
PHP Fatal error:  Uncaught Error: Class 'Pim\Bundle\CustomEntityBundle\PimCustomEntityBundle' not found in /home/sven/akeneo/pim-community-standard/app/AppKernel.php:24
Stack trace:

#0 /home/sven/akeneo/pim-community-standard/app/AppKernel.php(34): AppKernel->registerProjectBundles()
#1 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(488): AppKernel->registerBundles()
#2 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#3 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
#4 /home/sven/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Consol\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), $`

**Comment by simoncarre** [comment]
Hi @RiderTwix 
I've just updated README file for bundle installation. Do you still have an issue with loading for CustomEntityBundle?

**Comment by RiderTwix** [comment]
Unfortunately yes. When I add these lines: `
            new \Pim\Bundle\CustomEntityBundle\PimCustomEntityBundle(),
            new \ClickAndMortar\AdvancedCsvConnectorBundle\ClickAndMortarAdvancedCsvConnectorBundle(),`
I get the "akeneo_queue_daemon: ERROR (spawn error)" message again when executing the supervisorctl start akeneo_queue_daemon-command.

**Comment by simoncarre** [comment]
@RiderTwix Can you start you get me your supervisor logs? Or start your command directly in your terminal to get error?
