### ISSUE TITLE
No translation

### ISSUE THREAD

**Issue by Philippe-M** [ClickAndMortar/AdvancedCsvConnectorBundle#19]
I just installed the connector version 1.6, it appears in the list when I want to create an import or export but the text is not translated (I tried in French and English).

![image](https://user-images.githubusercontent.com/4558101/64959334-34405680-d891-11e9-9838-36464fd42274.png)

I'm use Akeneo 3.2.7 CE et AdvancedCsvConnectorBundle 1.6

**Comment by Philippe-M** [comment]
```
rm -Rf var/cache/*
rm -Rf web/js/translation/fr_FR.js
bin/console --env=prod oro:translation:dump fr_FR
```

**Comment by simoncarre** [comment]
Hello @Philippe-M,

I've update readme file to add some commands after install process. Do you already have issues?

**Comment by Philippe-M** [comment]
Hello @simoncarre,

After launching these commands I no longer have this problem. I have others but before I have to do complementary tests and I would create an issue to explain them and can be a solution.

**Comment by simoncarre** [comment]
Hello @Philippe-M,

Ok, thank you for your help.
