### ISSUE TITLE
Empty page after creation mapping

### ISSUE THREAD

**Issue by Philippe-M** [ClickAndMortar/AdvancedCsvConnectorBundle#20]
When I create an export template by selecting "Click And Mortar Advanced CSV Connector", after clicking on saved I have a blank page.

![image](https://user-images.githubusercontent.com/4558101/64960709-1c1e0680-d894-11e9-8132-bd7cf0265971.png)

![image](https://user-images.githubusercontent.com/4558101/64960726-26d89b80-d894-11e9-8dae-ce7f7b662390.png)

I do not have an error in apache or akeneo logs

I'm use akeneo 3.2.7 CE and AdvancedCsvConnector 1.6

**Comment by Philippe-M** [comment]
Will there be any incompatibility between Akeneo 3.2 and CustomEntity?

![image](https://user-images.githubusercontent.com/4558101/65022149-b92e7d00-d930-11e9-937d-7ff936d59fbc.png)

**Comment by Philippe-M** [comment]
I found.

I made the proposed modification on https://github.com/akeneo-labs/CustomEntityBundle/issues/207 then

```
rm -rf ./var/cache ./web/js ./web/css
bin/console --env=prod pim:installer:assets --symlink --clean;
bin/console cache:clear --env=prod
yarn run webpack
```

**Comment by simoncarre** [comment]
Thank you @Philippe-M,

I've updated readme file.
