### ISSUE TITLE
[Feature] Dupplicate mapping

### ISSUE THREAD

**Issue by Philippe-M** [ClickAndMortar/AdvancedCsvConnectorBundle#21]
Hello,

In a future version, it is planned the possibility of dupplicate a mapping. Sometimes there is little difference between two mapping and instead of doing everything again it would be easier to copy it.

**Comment by simoncarre** [comment]
Hello @Philippe-M,

Like other feature, it's not planned at the moment but it could be very convenient to have this option on the grid. Can you do a PR if you work on it?

Thank you for your support.

**Comment by Philippe-M** [comment]
Hello @simoncarre,

Sorry but unfortunately I do not have a good enough level for the dev myself.

**Comment by simoncarre** [comment]
A proper method is to create an export and import profiles for reference data. Export the desired mapping, update the necessary data and re-import it.
