### ISSUE TITLE
Error when test lua script

### ISSUE THREAD

**Issue by Philippe-M** [ClickAndMortar/AdvancedCsvConnectorBundle#27]
I updated with the latest version of the 1.6 CE branch and on the script creation page I leave the default values and just press the test button.

![image](https://user-images.githubusercontent.com/4558101/68405415-57e09880-0180-11ea-81b0-04ee6212a859.png)

Nothing happens and in the firefox debug tools I have this error :

```
16:46:50,907 Error: The route "candm_advanced_csv_connector_api_luaUpdater_test" does not exist. 2 main.min.js:1:943648
    i http://xxxxxxdev/dist/main.min.js?f0cd7ae10aa827e01d407b533e167e76:1
    m http://xxxxxxdev/dist/main.min.js?f0cd7ae10aa827e01d407b533e167e76:1
    click .AknButton--apply http://xxxxxxdev/dist/main.min.js?f0cd7ae10aa827e01d407b533e167e76:1
    click .AknButton--apply self-hosted:1025
    dispatch http://xxxxxxdev/dist/vendor.min.js?f0cd7ae10aa827e01d407b533e167e76:1
    handle http://xxxxxxdev/dist/vendor.min.js?f0cd7ae10aa827e01d407b533e167e76:1
```

**Comment by simoncarre** [comment]
Hello @Philippe-M,

Did you add this part in your file `app/config/routing.yml` ?

```
candm_advanced_csv_connector:
    prefix: /candm-advanced-csv-connector
    resource: "@ClickAndMortarAdvancedCsvConnectorBundle/Resources/config/routing.yml"
```

**Comment by Philippe-M** [comment]
thank you for the information. Actually this part was not present in the file and yet I am persuaded to have added during the installation ...
