### ISSUE TITLE
Not respecting the export order defined in a job

### ISSUE THREAD

**Issue by Philippe-M** [ClickAndMortar/AdvancedCsvConnectorBundle#29]
When exporting a product with a reference, the order of the columns defined in the export job is not respected.

I created a reference containing the following columns in this order with these mapping rules:
- sku -> refcial
- gencod -> gtin
- itmdes1 -> des30
- itmdes2 -> des80
- itmdes3 -> des240

I create a new export using this reference. By default, Akeneo sorts the columns alphabetically when exporting and ACCB follows the same rule. So in the export I select the fields to export and use the same order as in the reference. I export and unfortunately the order defines in the export is not preserved, it is sorted again in alphabetical order.

Result:
`des30;des80;des240;gtin;refcial`

I perform the same test using the standard Akeneo export and there is no problem. My export is in the order defined in the job.

This ticket is close to this https://github.com/ClickAndMortar/AdvancedCsvConnectorBundle/issues/22 but is not really adding a feature, it is rather the respect of a planned operation by Akeneo.

**Comment by simoncarre** [comment]
Hello @Philippe-M,

The selection of the attributes is not managed by the module (this part should be hidden in the import / export profile). We will implement the evolution to allow the choice in the order of the attributes.
