### ISSUE TITLE
Import failed when i use a LUA script

### ISSUE THREAD

**Issue by fatoldsun00** [ClickAndMortar/AdvancedCsvConnectorBundle#32]
Hi,

When i use transform field for attach LUA script my import failed without error log or summary.
Even a simple script like

`attributeValue="Bagage"
return attributeValue;`

BTW thanks for this plugin !

-------------------- Edit ---------------------------
Job import error log  says Class 'Lua' not found 

```
In ProductAdvancedReader.php line 385:

  Attempted to load class "Lua" from the global namespace.
  Did you forget a "use" statement?
```
Lua and pecl lua are installed and displayed in phpinfo. 
There a bundle or wrapper to install for symfony ?

Thank

**Comment by simoncarre** [comment]
Hello @fatoldsun00,

Can you try again in the latest version 1.6.11?
No, there is no need for an additional bundle at Symfony level. Just package `php-lua` and restart Apache/Nginx after installation.
