### ISSUE TITLE
Option "only on creation" = yes is not working

### ISSUE THREAD

**Issue by khoyer-reply** [ClickAndMortar/AdvancedCsvConnectorBundle#34]
We did the installation and the configuration of this connector regarding the documentation. We set 2 attributes (type text and textarea) at the import-mapping with the option "only on creation" = yes. But changes who where made after creation of the article at those 2 attributes at the pim, are always replaced by the values who are delivered through a later import with the same file. 
Those two attributes shall be imported only once, when the article is created, not when the article is updated through an import. Or is the option "only on creation" explicit for a static set value at the option "default value"? This is not clear at the documentation.

Used akeneo version: CE 3.2.17

**Comment by khoyer-reply** [comment]
Can anyone give a feedback to this issue, please?

**Comment by simoncarre** [comment]
Hello @khoyer-reply,

Which bundle version are you using? After a test on version **1.6.11**, the bundle seems to work well with a mapping of this type: 

![capture_001](https://user-images.githubusercontent.com/1229419/84029566-e295aa00-a992-11ea-8445-c26827361a76.png)

**Comment by khoyer-reply** [comment]
Thank you, after update to version 1.6.11 it works fine. The version 1.6.8 was installed so far.
