### ISSUE TITLE
404 page on lua creation

### ISSUE THREAD

**Issue by dankoz51** [ClickAndMortar/AdvancedCsvConnectorBundle#40]
I am getting 404 error when try and create a lua script
1. click create lua script
2. enter , test and test as the name and code
3 your directed to a URL like this https://devakeneo.xumulus.com/#/reference-data/rest/undefined/undefined
Further to that inspecting, the network tools show that 
https://devakeneo.xumulus.com/reference-data/rest/luaUpdater/create
This simply is returning hello

**Comment by dankoz51** [comment]
![Uploading Screen Shot 2020-10-06 at 9.32.03 AM.png…]()

**Comment by dankoz51** [comment]
This seems to be more of an issue with using the standard composer install, if I install from this git repo then it goes away. I think there is some older code with a debug statement that I was pulling out of the composer repo.

**Comment by simoncarre** [comment]
Hello @dankoz51,

Can you try with last version of the bundle? I have no issues on my side with Akeneo 4.0 and AdvancedCsvConnectorBundle 1.8.12

**Comment by dankoz51** [comment]
after reinstalling and getting 1.8.12 this seems to work, thanks
