### ISSUE TITLE
Not compatible with composer-plugin-api  2.0.0?

### ISSUE THREAD

**Issue by robertwallenweinconsulting** [ClickAndMortar/AdvancedCsvConnectorBundle#44]
Hello,
this failed to install on Akeneo 4.0.3 CE in the presence of composer 2.0. The error reads:

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
symfony/flex v1.6.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
akeneo/pim-community-dev v4.0.3 requires symfony/flex ^1.4 -> satisfiable by symfony/flex[v1.6.2].
akeneo/pim-community-dev is locked to version v4.0.3 and an update of this package was not requested.
```
Is this a known problem?

**Comment by simoncarre** [comment]
Hi @robertwallenweinconsulting,

Can you try with the new Akeneo 5.0 and new release of bundle?
I just installed it locally with composer 2.0 and I didn't have any issue.

**Comment by robertwallenweinconsulting** [comment]
Hi @simoncarre,
thanks for your replies. Unfortunately, at this time I have no access to a 5.0 test system to verify this. But I suppose it might be solved due to the all new version dependencies. However, this won't solve the issue for those clients, who will stick to Akeneo 4.x in production for various reasons. 
Anyway,I'll post, if I can spare the time to set up an 5.0 instance and test it.
