### ISSUE TITLE
Documentation on how to import metrics

### ISSUE THREAD

**Issue by michaelrachlitz** [ClickAndMortar/AdvancedCsvConnectorBundle#47]
I would like to request a lua guide on how to import metrics.

If I read the warning it says properties like length with a measurement type attribute requires an array with the key unit. I've attempted to return an array through lua script however, returning an array is giving results I dont understand.

If I return a single value, like for instance 10

`return 10`

The logged result is:
`length":[{"locale":null,"scope":null,"data":{"amount":10,"unit":null}}]`

which makes somewhat sense.

If I return the following:
`array = {}
array['unit'] = KILOGRAM
array['amount'] = attributeValue

return array`

the result is:
`length":[{"locale":null,"scope":null,"data":{"amount":null,"unit":Array}}]`

I have attempted multiple other array formats but the result remains the same. If I return an array the amount is null. I've also attempted returning comma separated values with no results.

**Comment by cedric-jeeper** [comment]
Hello,

You just to do this : 

```
return attributeValue .. " CENTIMETER";
```
