### ISSUE TITLE
Custom entity bundle requirement

### ISSUE THREAD

**Issue by andriusvo** [ClickAndMortar/AdvancedCsvConnectorBundle#48]
I see that in composer.json `akeneo-labs/custom-entity-bundle` required version of `7.0.*`, how can you require this version if this version is not released and not visible in packagist?

**Comment by simoncarre** [comment]
Hello @andriusvo,

Use our fork like explained in README file :wink: 
https://github.com/ClickAndMortar/AdvancedCsvConnectorBundle/blob/master/README.md
